#!/usr/bin/env bash
INPUT=$(cat)
FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE" ] || [ ! -f "$FILE" ]; then
  exit 0
fi

LOG="$CLAUDE_PROJECT_DIR/TODO_LOG.md"
MATCHES=$(grep -n -E 'TODO|FIXME|HACK|XXX' "$FILE" 2>/dev/null)

if [ -z "$MATCHES" ]; then
  exit 0
fi

# Crear header si el archivo no existe
if [ ! -f "$LOG" ]; then
  echo "# TODO Log" > "$LOG"
  echo "" >> "$LOG"
  echo "Auto-generated by Claude Code hook. Do not edit manually." >> "$LOG"
  echo "" >> "$LOG"
fi

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

echo "## [$TIMESTAMP] \`$FILE\`" >> "$LOG"
echo "" >> "$LOG"
echo "$MATCHES" | while IFS= read -r line; do
  echo "- \`$line\`" >> "$LOG"
done
echo "" >> "$LOG"
